# ==============================================================================
# Description:  Prepares the input files and metadata necessary for differential 
#               splicing analysis using LeafCutter. This includes filtering out 
#               QC-failed samples, compiling a list of junction files, and 
#               generating the pairwise contrast grouping files.
# Input:        ../1-mapping/data/metadata.tsv
# Output:       1. data/junction_files.txt (List of .junc paths for LeafCutter)
#               2. data/groups_*.tsv (2-col mapping files for each contrast)
#               3. data/contrasts.txt (List of contrast names for Slurm array)
# ==============================================================================

library(tidyverse)
library(glue)

# ------------------------------------------------------------------------------
# 1. Environment Setup
# ------------------------------------------------------------------------------
# Ensure required subdirectories exist
if (!file.exists("data")) dir.create("data")
if (!file.exists("results")) dir.create("results")

# ------------------------------------------------------------------------------
# 2. Metadata Import & Outlier Exclusion
# ------------------------------------------------------------------------------
meta <- 
    read_tsv("../1-mapping/data/metadata.tsv")

# Isolate sample IDs and remove specific outliers.
# Rationale: Sample 'unstday0_10028815_1' exhibited a low proportion of uniquely 
# mapped reads during the STAR alignment step, causing it to cluster as an extreme 
# outlier in downstream LeafCutter PCA (leafviz).
meta_filt <-
    meta |>
    select(sample_id) |>
    filter(sample_id != "unstday0_10028815_1")

# ------------------------------------------------------------------------------
# 3. Generate Junction File List
# ------------------------------------------------------------------------------
# LeafCutter's clustering step requires a plain text file containing the paths 
# to every `.junc` file generated by Regtools during mapping.
meta_filt |>
    mutate(juncfile = glue("../1-mapping/bam/{sample_id}.junc")) |>
    pull(juncfile) |>
    write_lines("./data/junction_files.txt")

# ------------------------------------------------------------------------------
# 4. Generate Pairwise Contrast Groupings
# ------------------------------------------------------------------------------
# Parse the sample IDs to extract the stimulation condition, donor, and replicate.
# We restrict the differential splicing analysis strictly to the first replicate.
samples_for_ds <- 
    meta_filt |>
    separate(sample_id, c("stim", "donor", "replic"), sep = "_", remove = FALSE) |>
    filter(replic == 1) 

# Generate all possible pairwise combinations between the selected stimulation 
# conditions to define our contrasts.
contrasts_df <- 
    combn(c("unstday0", "TLR7", "BCR", "DN2"), 2) |>
    t() |>
    as.data.frame() |>
    mutate(contrast = paste0(V1, "vs.", V2)) |>
    select(contrast, stim1 = V1, stim2 = V2) |>
    pivot_longer(-contrast) |>
    select(-name)

# Join the contrast definitions with the sample metadata, then split and write
# a separate 'groups' file for each contrast.
# LeafCutter requires these files to be tab-separated, contain exactly two columns
# (sample_id, condition), and have NO column headers.
left_join(contrasts_df, samples_for_ds, 
	  join_by(value == stim), 
	  relationship = "many-to-many") |>
    select(contrast, sample_id, group = value) |>
    group_by(contrast) |>
    nest() |>
    ungroup() |>
    mutate(file_name = glue("./data/groups_{contrast}.tsv")) |>
    select(data, file_name) |>
    pwalk(~write_tsv(.x, .y, col_names = FALSE))

# ------------------------------------------------------------------------------
# 5. Export Contrasts for Slurm Execution
# ------------------------------------------------------------------------------
# Save the exact names of the generated contrasts into a plain text file.
# This file will be read line-by-line by a downstream Slurm array script to 
# execute LeafCutter for each contrast in parallel.
contrasts_df |>
    distinct(contrast) |>
    pull(contrast) |>
    write_lines("./data/contrasts.txt")

