# ==============================================================================
# Description:  Prepares BED files for HOMER transcription factor motif enrichment 
#               analysis. It extracts significantly upregulated peaks (increased 
#               chromatin accessibility) for each stimulation condition and sets 
#               up the consensus peak set to be used as a custom background.
# Input:        1. ../2-differential_peaks/results/*_24vsunst_24.tsv (DESeq2 results)
#               2. ../1-processing/.../consensus_peaks.mLb.clN.bed (Consensus peaks)
# Output:       1. ./data/{stim}.bed (Target BED files for HOMER)
#               2. ./data/consensus.bed (Background BED file for HOMER)
#               3. ./data/stims.txt (List of conditions for downstream Slurm array)
# ==============================================================================

library(tidyverse)
library(glue)
    
# Ensure the data directory exists
if (!file.exists("data")) dir.create("data")

# ------------------------------------------------------------------------------
# 1. Target Peak Extraction
# ------------------------------------------------------------------------------
# Function to parse DESeq2 results and convert significant hits into BED format
process_bed <- function(s) {

    glue("../2-differential_peaks/results/{s}_24vsunst_24.tsv") |>
    read_tsv() |>
    # Filter for significantly more accessible peaks upon stimulation:
    # padj <= 0.01 and log2FoldChange >= 1 (at least a 2-fold increase)
    filter(!is.na(padj), padj <= 0.01, log2FoldChange >= 1) |>
    # Select and order columns to strictly match the standard BED format:
    # chr, start, end, name, score, strand
    select(Chr, Start, End, interval, log2FoldChange, Strand) |>
    # Round the log2FoldChange for a cleaner score column
    mutate(log2FoldChange = round(log2FoldChange, 2)) |>
    # Write headless BED file for HOMER input
    write_tsv(glue("./data/{s}.bed"), col_names = FALSE)
}

# Define the list of stimulation conditions
stims <- c("IL4", "TLR7", "BCR", "DN2")

# Save the list of stimulations for a downstream Slurm array script to iterate over
write_lines(stims, "./data/stims.txt")

# Apply the processing function to all stimulation conditions
walk(stims, process_bed)

# ------------------------------------------------------------------------------
# 2. Background Peak Extraction
# ------------------------------------------------------------------------------
# Read the consensus peak file generated by MACS2 in the nf-core pipeline.
# We use this as the background for HOMER rather than random genomic sequences. 
# This ensures HOMER only compares our target peaks against other known accessible 
# chromatin regions in B cells, preventing artifactual motif enrichment driven 
# by broad genomic GC-content differences.
consensus <- 
    "../1-processing/results/bwa/merged_library/macs2/narrow_peak/consensus/consensus_peaks.mLb.clN.bed" |>
    read_tsv(col_names = FALSE) |>
    arrange(X1, X2)

# Export the background BED file
write_tsv(consensus, "./data/consensus.bed", col_names = FALSE)

