---
title: "Low input RNA-seq design"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = "")
```

### Packages

```{r}
library(tidyverse)
library(cowplot)
```

## Data frame with the experimental design

```{r}
# Sample IDs
ind_id <- c("MGB-10092121", "HD01", "HD02", "MGB-10034466", "HD03", "HD04")

# Conditions
stims <- c("Unstim", "IL4", "BCR", "TLR7", "BCR+TLR7", "TLR9", "CD40L", "DN2")

# Timepoints
timeps <- paste(c(0, 4, 24, 48, 72), "hrs")

# Samples
expr_df <- expand_grid(ind_id, stims, timeps) %>%
    filter(!(stims %in% c("Unstim", "IL4") & timeps %in% c("48 hrs", "72 hrs"))) %>%
    filter(!(timeps == "0 hrs" & stims != "Unstim"))

# Replicates
## put all reps for HD01 in plate #1
## put all reps for HD03 in plate #2
n_reps <- 5

reps_df <- 
    bind_rows(filter(expr_df, ind_id == "HD01", timeps == "24 hrs", stims == "DN2") %>%
                  .[rep(seq_len(nrow(.)), each = n_reps), ],
              filter(expr_df, ind_id == "HD03", timeps == "24 hrs", stims == "DN2") %>%
                  .[rep(seq_len(nrow(.)), each = n_reps), ]) 

# remove the individuals from the original dataset to avoid redundancy 
expr_upd_df <- anti_join(expr_df, reps_df, by = c("ind_id", "timeps", "stims"))


# Reserve 9 wells for Maggie on plate #2
maggie_df <- 
    tibble(ind_id = "Maggie", stims = "Maggie", timeps = "Maggie") %>%
    .[rep(seq_len(nrow(.)), each = 9), ]

# Add blank wells evenly between plates
blanks_n <- (8 * 12 * 2) - (nrow(expr_upd_df) + nrow(reps_df) + nrow(maggie_df))

blanks_df <- 
    tibble(ind_id = rep("blank", blanks_n),
           stims = rep("blank", blanks_n),
           timeps = rep("blank", blanks_n))

# Put everything together
ind_order <- c("blank", "HD01", "HD03", "MGB-10034466", "HD02", "HD04", "MGB-10092121", "Maggie")

temp_df <- bind_rows(expr_upd_df, reps_df, blanks_df, maggie_df) %>%
    mutate(ind_id = factor(ind_id, levels = ind_order),
           timeps = factor(timeps, levels = str_sort(unique(timeps), numeric = TRUE))) %>%
    arrange(ind_id, stims, timeps) 

# Check if all samples from a given individual are in the same plate
temp_df %>%
    count(ind_id) %>%
    mutate(i = cumsum(n))

# Assign index and plate number
index_plate_df <- temp_df %>%
    mutate(index = seq_len(n()),
           plate = ifelse(between(index, 1, 96), "plate1", "plate2")) %>%
    group_by(ind_id, stims, timeps) %>%
    mutate(ind_id = as.character(ind_id),
           ind_id = ifelse(ind_id != "Maggie" & n() > 1, paste(ind_id, "rep", row_number()), ind_id)) %>% 
    ungroup()

# Randomize all samples that are not Maggie's
set.seed(1)
final_design <- 
    index_plate_df %>%
    filter(ind_id != "Maggie") %>%
    group_by(plate) %>%
    slice_sample(prop = 1) %>%
    ungroup() %>%
    bind_rows(filter(index_plate_df, ind_id == "Maggie")) %>%
    group_by(plate) %>%
    mutate(index = seq_len(n())) %>%
    ungroup() %>%
    arrange(plate, index)
```

## Plate array

```{r}
# create plate matrix
design_matrices <- final_design %>%
    split(.$plate) %>%
    map(~select(., -plate)) %>%
    map(~unite(., "ID", c(ind_id, stims, timeps), sep = "_")) %>%
    map(~mutate(., ID = recode(ID, 
                               "blank_blank_blank" = "BLANK", 
                               "Maggie_Maggie_Maggie" = "Maggie"))) %>%
    map(~pull(., ID)) %>%
    map(~matrix(data = ., nrow = 8, ncol = 12))
```

## Plot plate array 

```{r, fig.width=12, fig.height=12}
design_plot_list <- design_matrices %>%
    map(. %>% 
            as.data.frame() %>% 
            rowid_to_column("row") %>% 
            pivot_longer(-row, "column") %>%
            mutate(column = as.character(parse_number(column)),
                   column = factor(column, levels = 1:12),
                   row = factor(row, levels = rev(1:8)),
                   value = gsub("_", "\n", value))
        )

plate_plots <- design_plot_list %>%
    map(~ggplot(., aes(column, row)) +
            geom_tile(fill = "white", color = "black") +
            geom_text(aes(label = value), size = 2.5, lineheight = .8) +
            theme_minimal() +
            theme(axis.title = element_blank(),
                  plot.margin = margin(t = 1, b = 1, r = 1, l = 1, unit = "cm")))
    

plot_grid(plotlist = plate_plots, ncol = 1, 
          labels = c("Plate 1", "Plate 2"))
```

```{r, echo = FALSE, eval=FALSE}
ggsave("low_input_layout.pdf", width = 11, height = 8.5)
```


