# ==============================================================================
# Description:  Performs differential chromatin accessibility analysis on ATAC-seq 
#               consensus peaks using DESeq2. Adapted from the nf-core/atacseq 
#               (v1.2.2) featurecounts_deseq2.r script. 
# Input:        1. ../1-processing/data/samplesheet.csv
#               2. ../1-processing/results/bwa/.../consensus_peaks.mLb.clN.featureCounts.txt
# Output:       1. ./results/metadata.tsv (Cleaned metadata)
#               2. ./results/deseq2_data.Rdata (DESeq2 objects)
#               3. ./results/pcadata_*peaks.rds (PCA coordinates for visualization)
#               4. ./results/*vs*.tsv (Pairwise differential accessibility tables)
# ==============================================================================

library(DESeq2)
library(vsn)
library(BiocParallel)
library(tidyverse)
library(glue)

# Ensure output directory exists
if (!file.exists("results")) dir.create("results")

# ------------------------------------------------------------------------------
# 1. Metadata Parsing
# ------------------------------------------------------------------------------
# Parse the nf-core samplesheet to extract donor IDs dynamically from the FASTQ 
# file names using regex.
samplesheet <- 
    read_csv("../1-processing/data/samplesheet.csv") |>
    mutate(f1 = basename(fastq_1),
	   donor_id = str_extract(f1, "20221025_([^_]+).*", group = 1),
	   replic = paste0("REP", replicate)) |>
    select(condition = sample, replic, donor_id) |>
    distinct()

write_tsv(samplesheet, "./results/metadata.tsv")

# ------------------------------------------------------------------------------
# 2. Count Data Import & Formatting
# ------------------------------------------------------------------------------
# Import the consensus peak count matrix generated by featureCounts
dat <- 
    "../1-processing/results/bwa/merged_library/macs2/narrow_peak/consensus/consensus_peaks.mLb.clN.featureCounts.txt" |>
    read_table(skip = 1)

# Clean up column names by removing the BAM file suffixes
colnames(dat) <- gsub("\\.mLb\\.\\clN\\.sorted\\.bam", "", colnames(dat))

# Isolate the genomic interval metadata (Chrom, Start, End, Strand, Length)
interval_table <-
    dat |>
    select(Geneid:Length) |>
    column_to_rownames("Geneid")

# Organize samples sequentially by stimulation condition
samples_vec <- 
    c(
    sort(grep("unst_", colnames(dat), value = TRUE)),
    sort(grep("IL4_", colnames(dat), value = TRUE)),
    sort(grep("TLR7_", colnames(dat), value = TRUE)),
    sort(grep("BCR_", colnames(dat), value = TRUE)),
    sort(grep("DN2_", colnames(dat), value = TRUE))
    )

# Filter out the '3donors' pool. 
# We remove this prior to DESeq2 to ensure the paired statistical model only 
# processes single-donor biological replicates.
pool_samples <- 
    samplesheet |>
    filter(donor_id == "3donors") |>
    unite("sample_id", c(condition, replic), sep = "_") |>
    pull(sample_id)

count_table <- 
    dat |>
    select(Geneid, all_of(samples_vec)) |>
    select(-all_of(pool_samples)) |>
    column_to_rownames("Geneid")

# ------------------------------------------------------------------------------
# 3. DESeq2 Execution
# ------------------------------------------------------------------------------
# Build the experimental design matrix
coldata <- 
    tibble(sample_id = colnames(count_table)) |>
    separate(sample_id, c("stim", "tp", "replic"), sep = "_", remove = FALSE) |>
    unite("condition", c(stim, tp), sep = "_") |>
    left_join(samplesheet) |>
    select(-replic) |>
    mutate_at(vars(condition, donor_id), fct_inorder) |>
    column_to_rownames("sample_id")

# Initialize the DESeq2 object.
# Design controls for donor baseline differences before testing for condition effects.
dds <- 
    DESeqDataSetFromMatrix(countData = round(count_table), 
			   colData = coldata, 
			   design = ~ condition + donor_id)

# Run standard DESeq2 differential analysis
# NOTE FOR EXTERNAL USERS: MulticoreParam(4) dictates 4 CPU threads. Adjust as needed.
dds <- DESeq(dds, parallel = TRUE, BPPARAM = MulticoreParam(4))

# Perform regularized log transformation for downstream PCA/clustering
rld <- rlog(dds)

save(dds, rld, file = "./results/deseq2_data.Rdata")

# ------------------------------------------------------------------------------
# 4. PCA Coordinate Extraction
# ------------------------------------------------------------------------------
# Generate PCA data iteratively across different thresholds of highly variable peaks.
# Saving the raw data objects allows for downstream plotting.
walk(c(500, 1000, 2500, 5000, 10000), 
     function(x) {
	 DESeq2::plotPCA(rld, intgroup = "condition", ntop = x, returnData = TRUE) |>
	 write_rds(glue("./results/pcadata_{x}peaks.rds"))
     })

# ------------------------------------------------------------------------------
# 5. Differential Accessibility Output Generation
# ------------------------------------------------------------------------------
# Identify all unique biological conditions to build pairwise contrasts
comparisons <- 
    coldata$condition |>
    unique() |>
    as.character() |>
    combn(2)

# Loop through every possible pair of conditions, extract the DESeq2 results,
# attach the genomic coordinates (interval_table), and export.
for (idx in 1:ncol(comparisons)) {

    control_group <- comparisons[1, idx]
    treat_group <- comparisons[2, idx]
    control_samples <- filter(coldata, condition == control_group) |> rownames()
    treat_samples <- filter(coldata, condition == treat_group) |> rownames()

    results_da <- 
	results(dds, contrast = c("condition", treat_group, control_group))

    results_out <- 
	cbind(interval_table, as.data.frame(results_da)) |>
	as_tibble(rownames = "interval")

    write_tsv(results_out, glue("./results/{treat_group}vs{control_group}.tsv"))

}
